//
//  DrudgeStyleKit.swift
//  Drudge
//
//  Created by Todd Isaacs on 6/18/16.
//  Copyright (c) 2016 Nerd Waller. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class DrudgeStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let fUIBlue: UIColor = UIColor(red: 0.173, green: 0.243, blue: 0.314, alpha: 1.000)
        static let fUILight: UIColor = UIColor(red: 0.204, green: 0.596, blue: 0.859, alpha: 1.000)
        static let logoStroke: UIColor = DrudgeStyleKit.fUILight.colorWithAlpha(1)
        static let readArticle: UIColor = DrudgeStyleKit.fUIBlue.colorWithHighlight(0.4)
        static let unreadArticle: UIColor = DrudgeStyleKit.fUIBlue.colorWithShadow(0.1)
        static var imageOfRefresh: UIImage?
        static var refreshTargets: [AnyObject]?
        static var imageOfPicture: UIImage?
        static var pictureTargets: [AnyObject]?
        static var imageOfFilter: UIImage?
        static var filterTargets: [AnyObject]?
        static var imageOfNoFilter: UIImage?
        static var noFilterTargets: [AnyObject]?
        static var imageOfHeadline_icon: UIImage?
        static var headline_iconTargets: [AnyObject]?
        static var imageOfTop_story: UIImage?
        static var top_storyTargets: [AnyObject]?
        static var imageOfColumn: UIImage?
        static var columnTargets: [AnyObject]?
        static var imageOfDLogo: UIImage?
        static var dLogoTargets: [AnyObject]?
        static var imageOfDNavLogo: UIImage?
        static var dNavLogoTargets: [AnyObject]?
    }

    //// Colors

    public class var fUIBlue: UIColor { return Cache.fUIBlue }
    public class var fUILight: UIColor { return Cache.fUILight }
    public class var logoStroke: UIColor { return Cache.logoStroke }
    public class var readArticle: UIColor { return Cache.readArticle }
    public class var unreadArticle: UIColor { return Cache.unreadArticle }

    //// Drawing Methods

    public class func drawRefresh() {
        //// Color Declarations
        let fUIBBlue = UIColor(red: 0.161, green: 0.502, blue: 0.725, alpha: 1.000)

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        UIColor.blackColor().setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()


        //// Oval Drawing
        let ovalPath = UIBezierPath()
        ovalPath.moveToPoint(CGPoint(x: 31.09, y: 15))
        ovalPath.addCurveToPoint(CGPoint(x: 16.09, y: 30), controlPoint1: CGPoint(x: 22.81, y: 15), controlPoint2: CGPoint(x: 16.09, y: 21.72))
        ovalPath.addCurveToPoint(CGPoint(x: 31.09, y: 45), controlPoint1: CGPoint(x: 16.09, y: 38.28), controlPoint2: CGPoint(x: 22.81, y: 45))
        ovalPath.addCurveToPoint(CGPoint(x: 46.09, y: 30), controlPoint1: CGPoint(x: 39.37, y: 45), controlPoint2: CGPoint(x: 46.09, y: 38.28))
        fUIBBlue.setStroke()
        ovalPath.lineWidth = 8
        ovalPath.stroke()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: 30, y: 22.05))
        bezierPath.addLineToPoint(CGPoint(x: 41.25, y: 15.49))
        bezierPath.addLineToPoint(CGPoint(x: 30, y: 8))
        bezierPath.addLineToPoint(CGPoint(x: 30, y: 21.86))
        bezierPath.lineCapStyle = .Round;

        bezierPath.lineJoinStyle = .Round;

        fUIBBlue.setFill()
        bezierPath.fill()
        fUIBBlue.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
    }

    public class func drawPicture() {
        //// Color Declarations
        let fUIBBlue = UIColor(red: 0.161, green: 0.502, blue: 0.725, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 2.19, y: 9.02, width: 56.06, height: 41.72), cornerRadius: 3)
        UIColor.whiteColor().setFill()
        rectanglePath.fill()
        fUIBBlue.setStroke()
        rectanglePath.lineWidth = 2
        rectanglePath.stroke()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: 8.27, y: 44.37))
        bezierPath.addLineToPoint(CGPoint(x: 52.25, y: 44.51))
        bezierPath.addLineToPoint(CGPoint(x: 52.31, y: 28.71))
        bezierPath.addLineToPoint(CGPoint(x: 38.94, y: 17.25))
        bezierPath.addLineToPoint(CGPoint(x: 23.06, y: 32.19))
        bezierPath.addLineToPoint(CGPoint(x: 16.6, y: 27.32))
        bezierPath.addLineToPoint(CGPoint(x: 8.58, y: 36))
        bezierPath.addLineToPoint(CGPoint(x: 8.27, y: 44.37))
        bezierPath.closePath()
        UIColor.whiteColor().setFill()
        bezierPath.fill()
        fUIBBlue.setStroke()
        bezierPath.lineWidth = 2
        bezierPath.stroke()


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRect(x: 8.52, y: 14.7, width: 7.22, height: 6.59))
        UIColor.whiteColor().setFill()
        ovalPath.fill()
        fUIBBlue.setStroke()
        ovalPath.lineWidth = 2
        ovalPath.stroke()
    }

    public class func drawFilter() {
        //// Color Declarations
        let fUIBBlue = UIColor(red: 0.161, green: 0.502, blue: 0.725, alpha: 1.000)

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: 2.39, y: 2.6))
        bezierPath.addLineToPoint(CGPoint(x: 22.55, y: 2.6))
        bezierPath.addLineToPoint(CGPoint(x: 14.48, y: 11.86))
        bezierPath.addLineToPoint(CGPoint(x: 14.51, y: 23.13))
        bezierPath.addLineToPoint(CGPoint(x: 10.5, y: 20.54))
        bezierPath.addLineToPoint(CGPoint(x: 10.45, y: 12.01))
        bezierPath.addLineToPoint(CGPoint(x: 2.39, y: 2.6))
        bezierPath.closePath()
        bezierPath.lineCapStyle = .Round;

        bezierPath.lineJoinStyle = .Round;

        fUIBBlue.setStroke()
        bezierPath.lineWidth = 2
        bezierPath.stroke()
    }

    public class func drawNoFilter() {
        //// Color Declarations
        let fUIRed = UIColor(red: 0.906, green: 0.298, blue: 0.235, alpha: 1.000)
        let fUIBBlue = UIColor(red: 0.161, green: 0.502, blue: 0.725, alpha: 1.000)

        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPoint(x: 23.92, y: 5.43))
        bezier4Path.addCurveToPoint(CGPoint(x: 19.61, y: 9.84), controlPoint1: CGPoint(x: 23.92, y: 7.86), controlPoint2: CGPoint(x: 21.99, y: 9.84))
        bezier4Path.addCurveToPoint(CGPoint(x: 17.02, y: 8.94), controlPoint1: CGPoint(x: 18.64, y: 9.84), controlPoint2: CGPoint(x: 17.74, y: 9.5))
        bezier4Path.addCurveToPoint(CGPoint(x: 14.48, y: 11.86), controlPoint1: CGPoint(x: 15.61, y: 10.56), controlPoint2: CGPoint(x: 14.48, y: 11.86))
        bezier4Path.addLineToPoint(CGPoint(x: 14.51, y: 23.13))
        bezier4Path.addLineToPoint(CGPoint(x: 10.5, y: 20.54))
        bezier4Path.addLineToPoint(CGPoint(x: 10.45, y: 12.01))
        bezier4Path.addLineToPoint(CGPoint(x: 2.39, y: 2.6))
        bezier4Path.addCurveToPoint(CGPoint(x: 16.31, y: 2.6), controlPoint1: CGPoint(x: 2.39, y: 2.6), controlPoint2: CGPoint(x: 10.39, y: 2.6))
        bezier4Path.addCurveToPoint(CGPoint(x: 19.61, y: 1.03), controlPoint1: CGPoint(x: 17.1, y: 1.64), controlPoint2: CGPoint(x: 18.29, y: 1.03))
        bezier4Path.addCurveToPoint(CGPoint(x: 23.92, y: 5.43), controlPoint1: CGPoint(x: 21.99, y: 1.03), controlPoint2: CGPoint(x: 23.92, y: 3))
        bezier4Path.closePath()
        bezier4Path.lineJoinStyle = .Round;

        fUIBBlue.setStroke()
        bezier4Path.lineWidth = 2
        bezier4Path.stroke()


        //// Group
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: 21.54, y: 3.21))
        bezierPath.addCurveToPoint(CGPoint(x: 21.6, y: 3.96), controlPoint1: CGPoint(x: 21.77, y: 3.44), controlPoint2: CGPoint(x: 21.78, y: 3.76))
        bezierPath.addCurveToPoint(CGPoint(x: 20.37, y: 5.39), controlPoint1: CGPoint(x: 21.6, y: 3.96), controlPoint2: CGPoint(x: 20.67, y: 5.05))
        bezierPath.addCurveToPoint(CGPoint(x: 21.61, y: 6.78), controlPoint1: CGPoint(x: 21.03, y: 6.13), controlPoint2: CGPoint(x: 21.61, y: 6.78))
        bezierPath.addCurveToPoint(CGPoint(x: 21.6, y: 7.5), controlPoint1: CGPoint(x: 21.78, y: 6.98), controlPoint2: CGPoint(x: 21.78, y: 7.3))
        bezierPath.addCurveToPoint(CGPoint(x: 20.94, y: 7.49), controlPoint1: CGPoint(x: 21.41, y: 7.69), controlPoint2: CGPoint(x: 21.12, y: 7.69))
        bezierPath.addCurveToPoint(CGPoint(x: 19.74, y: 6.13), controlPoint1: CGPoint(x: 20.94, y: 7.49), controlPoint2: CGPoint(x: 20.38, y: 6.86))
        bezierPath.addCurveToPoint(CGPoint(x: 18.53, y: 7.54), controlPoint1: CGPoint(x: 19.23, y: 6.73), controlPoint2: CGPoint(x: 18.53, y: 7.54))
        bezierPath.addCurveToPoint(CGPoint(x: 17.88, y: 7.56), controlPoint1: CGPoint(x: 18.36, y: 7.74), controlPoint2: CGPoint(x: 18.06, y: 7.75))
        bezierPath.addCurveToPoint(CGPoint(x: 17.86, y: 6.84), controlPoint1: CGPoint(x: 17.69, y: 7.37), controlPoint2: CGPoint(x: 17.68, y: 7.05))
        bezierPath.addCurveToPoint(CGPoint(x: 19.1, y: 5.4), controlPoint1: CGPoint(x: 17.86, y: 6.84), controlPoint2: CGPoint(x: 18.69, y: 5.87))
        bezierPath.addCurveToPoint(CGPoint(x: 17.85, y: 3.99), controlPoint1: CGPoint(x: 18.43, y: 4.65), controlPoint2: CGPoint(x: 17.85, y: 3.99))
        bezierPath.addCurveToPoint(CGPoint(x: 17.86, y: 3.28), controlPoint1: CGPoint(x: 17.67, y: 3.79), controlPoint2: CGPoint(x: 17.68, y: 3.47))
        bezierPath.addCurveToPoint(CGPoint(x: 18.52, y: 3.29), controlPoint1: CGPoint(x: 18.06, y: 3.08), controlPoint2: CGPoint(x: 18.34, y: 3.1))
        bezierPath.addCurveToPoint(CGPoint(x: 19.73, y: 4.66), controlPoint1: CGPoint(x: 18.52, y: 3.29), controlPoint2: CGPoint(x: 19.08, y: 3.93))
        bezierPath.addCurveToPoint(CGPoint(x: 20.93, y: 3.27), controlPoint1: CGPoint(x: 20.05, y: 4.29), controlPoint2: CGPoint(x: 20.93, y: 3.27))
        bezierPath.addCurveToPoint(CGPoint(x: 21.58, y: 3.25), controlPoint1: CGPoint(x: 21.1, y: 3.07), controlPoint2: CGPoint(x: 21.39, y: 3.06))
        bezierPath.addLineToPoint(CGPoint(x: 21.54, y: 3.21))
        bezierPath.closePath()
        fUIRed.setFill()
        bezierPath.fill()
    }

    public class func drawHeadline_icon() {
        //// Color Declarations
        let fUIRed = UIColor(red: 0.906, green: 0.298, blue: 0.235, alpha: 1.000)
        let fUIBBlue = UIColor(red: 0.161, green: 0.502, blue: 0.725, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 3.71, y: 2.02, width: 12.62, height: 15.83), cornerRadius: 1)
        fUIBBlue.setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 6, y: 4.25, width: 8, height: 7.66))
        fUIBBlue.setStroke()
        rectangle2Path.lineWidth = 1
        rectangle2Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPoint(x: 5.58, y: 14.07))
        bezier4Path.addLineToPoint(CGPoint(x: 14.55, y: 14.03))
        fUIBBlue.setStroke()
        bezier4Path.lineWidth = 0.5
        bezier4Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPoint(x: 5.64, y: 15.91))
        bezier3Path.addLineToPoint(CGPoint(x: 14.61, y: 15.87))
        fUIBBlue.setStroke()
        bezier3Path.lineWidth = 0.5
        bezier3Path.stroke()


        //// Star Drawing
        let starPath = UIBezierPath()
        starPath.moveToPoint(CGPoint(x: 10.03, y: 6.19))
        starPath.addLineToPoint(CGPoint(x: 10.49, y: 7.56))
        starPath.addLineToPoint(CGPoint(x: 11.93, y: 7.57))
        starPath.addLineToPoint(CGPoint(x: 10.77, y: 8.43))
        starPath.addLineToPoint(CGPoint(x: 11.2, y: 9.81))
        starPath.addLineToPoint(CGPoint(x: 10.03, y: 8.97))
        starPath.addLineToPoint(CGPoint(x: 8.85, y: 9.81))
        starPath.addLineToPoint(CGPoint(x: 9.28, y: 8.43))
        starPath.addLineToPoint(CGPoint(x: 8.12, y: 7.57))
        starPath.addLineToPoint(CGPoint(x: 9.57, y: 7.56))
        starPath.closePath()
        fUIRed.setFill()
        starPath.fill()
        fUIRed.setStroke()
        starPath.lineWidth = 1
        starPath.stroke()
    }

    public class func drawTop_story() {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 3.71, y: 2.02, width: 12.62, height: 15.83), cornerRadius: 1)
        DrudgeStyleKit.fUILight.setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: 5.62, y: 10.5))
        bezierPath.addLineToPoint(CGPoint(x: 14.59, y: 10.45))
        DrudgeStyleKit.fUILight.setStroke()
        bezierPath.lineWidth = 0.5
        bezierPath.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPoint(x: 5.63, y: 12.16))
        bezier2Path.addLineToPoint(CGPoint(x: 14.6, y: 12.11))
        DrudgeStyleKit.fUILight.setStroke()
        bezier2Path.lineWidth = 0.5
        bezier2Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPoint(x: 5.58, y: 14.07))
        bezier4Path.addLineToPoint(CGPoint(x: 14.55, y: 14.03))
        DrudgeStyleKit.fUILight.setStroke()
        bezier4Path.lineWidth = 0.5
        bezier4Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPoint(x: 5.64, y: 15.91))
        bezier3Path.addLineToPoint(CGPoint(x: 14.61, y: 15.87))
        DrudgeStyleKit.fUILight.setStroke()
        bezier3Path.lineWidth = 0.5
        bezier3Path.stroke()


        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.moveToPoint(CGPoint(x: 5.65, y: 5.23))
        bezier5Path.addLineToPoint(CGPoint(x: 14.61, y: 5.18))
        DrudgeStyleKit.fUILight.setStroke()
        bezier5Path.lineWidth = 0.5
        bezier5Path.stroke()


        //// Bezier 6 Drawing
        let bezier6Path = UIBezierPath()
        bezier6Path.moveToPoint(CGPoint(x: 5.65, y: 6.89))
        bezier6Path.addLineToPoint(CGPoint(x: 14.62, y: 6.84))
        DrudgeStyleKit.fUILight.setStroke()
        bezier6Path.lineWidth = 0.5
        bezier6Path.stroke()


        //// Bezier 7 Drawing
        let bezier7Path = UIBezierPath()
        bezier7Path.moveToPoint(CGPoint(x: 5.6, y: 8.8))
        bezier7Path.addLineToPoint(CGPoint(x: 14.57, y: 8.75))
        DrudgeStyleKit.fUILight.setStroke()
        bezier7Path.lineWidth = 0.5
        bezier7Path.stroke()


        //// Bezier 8 Drawing
        let bezier8Path = UIBezierPath()
        DrudgeStyleKit.fUILight.setStroke()
        bezier8Path.lineWidth = 1
        bezier8Path.stroke()


        //// Bezier 9 Drawing
        let bezier9Path = UIBezierPath()
        bezier9Path.moveToPoint(CGPoint(x: 9.07, y: 16.15))
        bezier9Path.addLineToPoint(CGPoint(x: 9.07, y: 8.97))
        bezier9Path.addLineToPoint(CGPoint(x: 5.83, y: 8.97))
        bezier9Path.addLineToPoint(CGPoint(x: 10.23, y: 4.03))
        bezier9Path.addLineToPoint(CGPoint(x: 14.86, y: 8.97))
        bezier9Path.addLineToPoint(CGPoint(x: 11.62, y: 8.97))
        bezier9Path.addLineToPoint(CGPoint(x: 11.62, y: 16.15))
        bezier9Path.addLineToPoint(CGPoint(x: 9.07, y: 16.15))
        bezier9Path.closePath()
        bezier9Path.lineJoinStyle = .Round;

        DrudgeStyleKit.fUILight.setFill()
        bezier9Path.fill()
        DrudgeStyleKit.fUILight.setStroke()
        bezier9Path.lineWidth = 0.5
        bezier9Path.stroke()
    }

    public class func drawColumn() {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 3.71, y: 2.02, width: 12.62, height: 15.83), cornerRadius: 1)
        DrudgeStyleKit.fUILight.setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 6, y: 4.5, width: 3, height: 11))
        DrudgeStyleKit.fUILight.setFill()
        rectangle2Path.fill()
        DrudgeStyleKit.fUILight.setStroke()
        rectangle2Path.lineWidth = 0.5
        rectangle2Path.stroke()


        //// Rectangle 3 Drawing
        let rectangle3Path = UIBezierPath(rect: CGRect(x: 11, y: 4.5, width: 3, height: 11))
        DrudgeStyleKit.fUILight.setFill()
        rectangle3Path.fill()
        DrudgeStyleKit.fUILight.setStroke()
        rectangle3Path.lineWidth = 0.5
        rectangle3Path.stroke()


        //// Bezier 8 Drawing
        let bezier8Path = UIBezierPath()
        DrudgeStyleKit.fUILight.setStroke()
        bezier8Path.lineWidth = 1
        bezier8Path.stroke()
    }

    public class func drawDLogo() {
        //// Color Declarations
        let fUIWhite = UIColor(red: 0.983, green: 0.982, blue: 0.992, alpha: 1.000)
        let fUIBBlue = UIColor(red: 0.161, green: 0.502, blue: 0.725, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0.34, y: 1, width: 513.29, height: 510.85))
        fUIBBlue.setFill()
        rectanglePath.fill()


        //// Text Drawing
        let textPath = UIBezierPath()
        textPath.moveToPoint(CGPoint(x: 94.07, y: 452.73))
        textPath.addLineToPoint(CGPoint(x: 94.07, y: 59.76))
        textPath.addLineToPoint(CGPoint(x: 263.21, y: 59.76))
        textPath.addCurveToPoint(CGPoint(x: 403.14, y: 108.22), controlPoint1: CGPoint(x: 324.1, y: 59.76), controlPoint2: CGPoint(x: 370.75, y: 75.91))
        textPath.addCurveToPoint(CGPoint(x: 451.73, y: 248.01), controlPoint1: CGPoint(x: 435.54, y: 140.52), controlPoint2: CGPoint(x: 451.73, y: 187.12))
        textPath.addCurveToPoint(CGPoint(x: 400.22, y: 398.96), controlPoint1: CGPoint(x: 451.73, y: 312.8), controlPoint2: CGPoint(x: 434.56, y: 363.12))
        textPath.addCurveToPoint(CGPoint(x: 256.04, y: 452.73), controlPoint1: CGPoint(x: 365.88, y: 434.81), controlPoint2: CGPoint(x: 317.82, y: 452.73))
        textPath.addLineToPoint(CGPoint(x: 94.07, y: 452.73))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 175.85, y: 396.97))
        textPath.addLineToPoint(CGPoint(x: 236.92, y: 396.97))
        textPath.addCurveToPoint(CGPoint(x: 333.18, y: 361.26), controlPoint1: CGPoint(x: 279.94, y: 396.97), controlPoint2: CGPoint(x: 312.02, y: 385.07))
        textPath.addCurveToPoint(CGPoint(x: 364.91, y: 252.79), controlPoint1: CGPoint(x: 354.33, y: 337.45), controlPoint2: CGPoint(x: 364.91, y: 301.29))
        textPath.addCurveToPoint(CGPoint(x: 339.42, y: 159.06), controlPoint1: CGPoint(x: 364.91, y: 215.27), controlPoint2: CGPoint(x: 356.41, y: 184.02))
        textPath.addCurveToPoint(CGPoint(x: 297.2, y: 123.48), controlPoint1: CGPoint(x: 327.73, y: 141.89), controlPoint2: CGPoint(x: 313.66, y: 130.03))
        textPath.addCurveToPoint(CGPoint(x: 225.24, y: 113.66), controlPoint1: CGPoint(x: 280.74, y: 116.93), controlPoint2: CGPoint(x: 256.75, y: 113.66))
        textPath.addLineToPoint(CGPoint(x: 175.85, y: 113.66))
        textPath.addLineToPoint(CGPoint(x: 175.85, y: 396.97))
        textPath.closePath()
        fUIWhite.setFill()
        textPath.fill()
        fUIWhite.setStroke()
        textPath.lineWidth = 8
        textPath.stroke()
    }

    public class func drawUpdateButton() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 0, y: 0, width: 93, height: 27), cornerRadius: 8)
        DrudgeStyleKit.fUIBlue.setFill()
        rectanglePath.fill()


        //// Text Drawing
        let textRect = CGRect(x: 20.75, y: 3, width: 67.26, height: 21)
        let textPath = UIBezierPath(rect: textRect)
        DrudgeStyleKit.fUIBlue.setFill()
        textPath.fill()
        let textTextContent = NSString(string: "Updates")
        let textStyle = NSMutableParagraphStyle()
        textStyle.alignment = .Left

        let textFontAttributes = [NSFontAttributeName: UIFont.systemFontOfSize(UIFont.labelFontSize()), NSForegroundColorAttributeName: UIColor.whiteColor(), NSParagraphStyleAttributeName: textStyle]

        let textTextHeight: CGFloat = textTextContent.boundingRectWithSize(CGSize(width: textRect.width, height: CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, textRect)
        textTextContent.drawInRect(CGRect(x: textRect.minX, y: textRect.minY + (textRect.height - textTextHeight) / 2, width: textRect.width, height: textTextHeight), withAttributes: textFontAttributes)
        CGContextRestoreGState(context)


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: 11, y: 20))
        bezierPath.addLineToPoint(CGPoint(x: 11, y: 5.98))
        bezierPath.addLineToPoint(CGPoint(x: 6.52, y: 11.48))
        bezierPath.addLineToPoint(CGPoint(x: 14.75, y: 11.48))
        bezierPath.addLineToPoint(CGPoint(x: 11, y: 5.98))
        bezierPath.lineJoinStyle = .Round;

        UIColor.whiteColor().setFill()
        bezierPath.fill()
        UIColor.whiteColor().setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
    }

    public class func drawDNavLogo() {
        //// Color Declarations
        let fUIWhite = UIColor(red: 0.983, green: 0.982, blue: 0.992, alpha: 1.000)
        let fUIBBlue = UIColor(red: 0.161, green: 0.502, blue: 0.725, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 0.82, y: 1.28, width: 23, height: 23), cornerRadius: 5)
        fUIBBlue.setFill()
        rectanglePath.fill()


        //// Text Drawing
        let textPath = UIBezierPath()
        textPath.moveToPoint(CGPoint(x: 6.48, y: 19.24))
        textPath.addLineToPoint(CGPoint(x: 6.48, y: 5.98))
        textPath.addLineToPoint(CGPoint(x: 12.45, y: 5.98))
        textPath.addCurveToPoint(CGPoint(x: 17.38, y: 7.62), controlPoint1: CGPoint(x: 14.59, y: 5.98), controlPoint2: CGPoint(x: 16.24, y: 6.53))
        textPath.addCurveToPoint(CGPoint(x: 19.09, y: 12.33), controlPoint1: CGPoint(x: 18.52, y: 8.71), controlPoint2: CGPoint(x: 19.09, y: 10.28))
        textPath.addCurveToPoint(CGPoint(x: 17.27, y: 17.43), controlPoint1: CGPoint(x: 19.09, y: 14.52), controlPoint2: CGPoint(x: 18.49, y: 16.22))
        textPath.addCurveToPoint(CGPoint(x: 12.19, y: 19.24), controlPoint1: CGPoint(x: 16.06, y: 18.64), controlPoint2: CGPoint(x: 14.37, y: 19.24))
        textPath.addLineToPoint(CGPoint(x: 6.48, y: 19.24))
        textPath.closePath()
        textPath.moveToPoint(CGPoint(x: 9.37, y: 17.36))
        textPath.addLineToPoint(CGPoint(x: 11.52, y: 17.36))
        textPath.addCurveToPoint(CGPoint(x: 14.91, y: 16.15), controlPoint1: CGPoint(x: 13.03, y: 17.36), controlPoint2: CGPoint(x: 14.17, y: 16.96))
        textPath.addCurveToPoint(CGPoint(x: 16.03, y: 12.5), controlPoint1: CGPoint(x: 15.66, y: 15.35), controlPoint2: CGPoint(x: 16.03, y: 14.13))
        textPath.addCurveToPoint(CGPoint(x: 15.13, y: 9.33), controlPoint1: CGPoint(x: 16.03, y: 11.23), controlPoint2: CGPoint(x: 15.73, y: 10.18))
        textPath.addCurveToPoint(CGPoint(x: 13.64, y: 8.13), controlPoint1: CGPoint(x: 14.72, y: 8.75), controlPoint2: CGPoint(x: 14.22, y: 8.35))
        textPath.addCurveToPoint(CGPoint(x: 11.11, y: 7.8), controlPoint1: CGPoint(x: 13.06, y: 7.91), controlPoint2: CGPoint(x: 12.22, y: 7.8))
        textPath.addLineToPoint(CGPoint(x: 9.37, y: 7.8))
        textPath.addLineToPoint(CGPoint(x: 9.37, y: 17.36))
        textPath.closePath()
        fUIWhite.setFill()
        textPath.fill()
        fUIWhite.setStroke()
        textPath.lineWidth = 0
        textPath.stroke()


        //// Text 3 Drawing
        let text3Path = UIBezierPath()
        text3Path.moveToPoint(CGPoint(x: 29.53, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 29.53, y: 4.51))
        text3Path.addLineToPoint(CGPoint(x: 34.98, y: 4.51))
        text3Path.addCurveToPoint(CGPoint(x: 39.5, y: 6.39), controlPoint1: CGPoint(x: 36.95, y: 4.51), controlPoint2: CGPoint(x: 38.45, y: 5.13))
        text3Path.addCurveToPoint(CGPoint(x: 41.06, y: 11.81), controlPoint1: CGPoint(x: 40.54, y: 7.64), controlPoint2: CGPoint(x: 41.06, y: 9.45))
        text3Path.addCurveToPoint(CGPoint(x: 39.4, y: 17.67), controlPoint1: CGPoint(x: 41.06, y: 14.32), controlPoint2: CGPoint(x: 40.51, y: 16.28))
        text3Path.addCurveToPoint(CGPoint(x: 34.75, y: 19.75), controlPoint1: CGPoint(x: 38.29, y: 19.06), controlPoint2: CGPoint(x: 36.74, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 29.53, y: 19.75))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 32.16, y: 17.59))
        text3Path.addLineToPoint(CGPoint(x: 34.13, y: 17.59))
        text3Path.addCurveToPoint(CGPoint(x: 37.24, y: 16.2), controlPoint1: CGPoint(x: 35.52, y: 17.59), controlPoint2: CGPoint(x: 36.56, y: 17.13))
        text3Path.addCurveToPoint(CGPoint(x: 38.26, y: 12), controlPoint1: CGPoint(x: 37.92, y: 15.28), controlPoint2: CGPoint(x: 38.26, y: 13.88))
        text3Path.addCurveToPoint(CGPoint(x: 37.44, y: 8.36), controlPoint1: CGPoint(x: 38.26, y: 10.54), controlPoint2: CGPoint(x: 37.99, y: 9.33))
        text3Path.addCurveToPoint(CGPoint(x: 36.08, y: 6.98), controlPoint1: CGPoint(x: 37.06, y: 7.69), controlPoint2: CGPoint(x: 36.61, y: 7.23))
        text3Path.addCurveToPoint(CGPoint(x: 33.76, y: 6.6), controlPoint1: CGPoint(x: 35.55, y: 6.72), controlPoint2: CGPoint(x: 34.77, y: 6.6))
        text3Path.addLineToPoint(CGPoint(x: 32.16, y: 6.6))
        text3Path.addLineToPoint(CGPoint(x: 32.16, y: 17.59))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 43.43, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 43.43, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 45.97, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 45.97, y: 10.57))
        text3Path.addCurveToPoint(CGPoint(x: 48.97, y: 8.18), controlPoint1: CGPoint(x: 46.63, y: 8.98), controlPoint2: CGPoint(x: 47.63, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 49.44, y: 8.25), controlPoint1: CGPoint(x: 49.13, y: 8.18), controlPoint2: CGPoint(x: 49.28, y: 8.2))
        text3Path.addLineToPoint(CGPoint(x: 49.44, y: 10.97))
        text3Path.addCurveToPoint(CGPoint(x: 48.44, y: 10.73), controlPoint1: CGPoint(x: 49.08, y: 10.81), controlPoint2: CGPoint(x: 48.74, y: 10.73))
        text3Path.addCurveToPoint(CGPoint(x: 45.97, y: 12.57), controlPoint1: CGPoint(x: 47.43, y: 10.73), controlPoint2: CGPoint(x: 46.6, y: 11.34))
        text3Path.addLineToPoint(CGPoint(x: 45.97, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 43.43, y: 19.75))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 57.22, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 57.22, y: 17.62))
        text3Path.addCurveToPoint(CGPoint(x: 54.02, y: 20.01), controlPoint1: CGPoint(x: 56.4, y: 19.21), controlPoint2: CGPoint(x: 55.33, y: 20.01))
        text3Path.addCurveToPoint(CGPoint(x: 52.03, y: 19.05), controlPoint1: CGPoint(x: 53.18, y: 20.01), controlPoint2: CGPoint(x: 52.52, y: 19.69))
        text3Path.addCurveToPoint(CGPoint(x: 51.31, y: 16.44), controlPoint1: CGPoint(x: 51.55, y: 18.41), controlPoint2: CGPoint(x: 51.31, y: 17.54))
        text3Path.addLineToPoint(CGPoint(x: 51.31, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 53.84, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 53.84, y: 15.68))
        text3Path.addCurveToPoint(CGPoint(x: 54.91, y: 17.61), controlPoint1: CGPoint(x: 53.84, y: 16.97), controlPoint2: CGPoint(x: 54.2, y: 17.61))
        text3Path.addCurveToPoint(CGPoint(x: 57.22, y: 15.56), controlPoint1: CGPoint(x: 55.71, y: 17.61), controlPoint2: CGPoint(x: 56.48, y: 16.93))
        text3Path.addLineToPoint(CGPoint(x: 57.22, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 59.76, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 59.76, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 57.22, y: 19.75))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 68.84, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 68.84, y: 17.62))
        text3Path.addCurveToPoint(CGPoint(x: 65.77, y: 20.01), controlPoint1: CGPoint(x: 68.19, y: 19.21), controlPoint2: CGPoint(x: 67.17, y: 20.01))
        text3Path.addCurveToPoint(CGPoint(x: 63.11, y: 18.52), controlPoint1: CGPoint(x: 64.64, y: 20.01), controlPoint2: CGPoint(x: 63.75, y: 19.51))
        text3Path.addCurveToPoint(CGPoint(x: 62.14, y: 14.41), controlPoint1: CGPoint(x: 62.46, y: 17.52), controlPoint2: CGPoint(x: 62.14, y: 16.15))
        text3Path.addCurveToPoint(CGPoint(x: 63.23, y: 9.87), controlPoint1: CGPoint(x: 62.14, y: 12.51), controlPoint2: CGPoint(x: 62.5, y: 11))
        text3Path.addCurveToPoint(CGPoint(x: 66.16, y: 8.18), controlPoint1: CGPoint(x: 63.96, y: 8.75), controlPoint2: CGPoint(x: 64.94, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 68.84, y: 9.58), controlPoint1: CGPoint(x: 67.15, y: 8.18), controlPoint2: CGPoint(x: 68.04, y: 8.65))
        text3Path.addLineToPoint(CGPoint(x: 68.84, y: 3.49))
        text3Path.addLineToPoint(CGPoint(x: 71.39, y: 3.49))
        text3Path.addLineToPoint(CGPoint(x: 71.39, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 68.84, y: 19.75))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 68.84, y: 11.4))
        text3Path.addCurveToPoint(CGPoint(x: 66.88, y: 10.16), controlPoint1: CGPoint(x: 68.23, y: 10.57), controlPoint2: CGPoint(x: 67.58, y: 10.16))
        text3Path.addCurveToPoint(CGPoint(x: 65.39, y: 11.24), controlPoint1: CGPoint(x: 66.26, y: 10.16), controlPoint2: CGPoint(x: 65.76, y: 10.52))
        text3Path.addCurveToPoint(CGPoint(x: 64.84, y: 14.15), controlPoint1: CGPoint(x: 65.02, y: 11.96), controlPoint2: CGPoint(x: 64.84, y: 12.93))
        text3Path.addCurveToPoint(CGPoint(x: 66.69, y: 17.62), controlPoint1: CGPoint(x: 64.84, y: 16.46), controlPoint2: CGPoint(x: 65.45, y: 17.62))
        text3Path.addCurveToPoint(CGPoint(x: 68.84, y: 15.88), controlPoint1: CGPoint(x: 67.44, y: 17.62), controlPoint2: CGPoint(x: 68.16, y: 17.04))
        text3Path.addLineToPoint(CGPoint(x: 68.84, y: 11.4))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 74.62, y: 23.27))
        text3Path.addLineToPoint(CGPoint(x: 74.82, y: 21.05))
        text3Path.addCurveToPoint(CGPoint(x: 77.81, y: 21.92), controlPoint1: CGPoint(x: 75.87, y: 21.63), controlPoint2: CGPoint(x: 76.86, y: 21.92))
        text3Path.addCurveToPoint(CGPoint(x: 79.84, y: 21.2), controlPoint1: CGPoint(x: 78.75, y: 21.92), controlPoint2: CGPoint(x: 79.42, y: 21.68))
        text3Path.addCurveToPoint(CGPoint(x: 80.47, y: 18.86), controlPoint1: CGPoint(x: 80.26, y: 20.72), controlPoint2: CGPoint(x: 80.47, y: 19.94))
        text3Path.addLineToPoint(CGPoint(x: 80.47, y: 17.31))
        text3Path.addCurveToPoint(CGPoint(x: 77.41, y: 19.75), controlPoint1: CGPoint(x: 79.85, y: 18.94), controlPoint2: CGPoint(x: 78.83, y: 19.75))
        text3Path.addCurveToPoint(CGPoint(x: 74.75, y: 18.24), controlPoint1: CGPoint(x: 76.29, y: 19.75), controlPoint2: CGPoint(x: 75.4, y: 19.25))
        text3Path.addCurveToPoint(CGPoint(x: 73.76, y: 14.16), controlPoint1: CGPoint(x: 74.09, y: 17.24), controlPoint2: CGPoint(x: 73.76, y: 15.88))
        text3Path.addCurveToPoint(CGPoint(x: 74.87, y: 9.82), controlPoint1: CGPoint(x: 73.76, y: 12.35), controlPoint2: CGPoint(x: 74.13, y: 10.91))
        text3Path.addCurveToPoint(CGPoint(x: 77.8, y: 8.18), controlPoint1: CGPoint(x: 75.6, y: 8.73), controlPoint2: CGPoint(x: 76.58, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 80.47, y: 9.58), controlPoint1: CGPoint(x: 78.76, y: 8.18), controlPoint2: CGPoint(x: 79.65, y: 8.65))
        text3Path.addLineToPoint(CGPoint(x: 80.73, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 83.01, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 83.01, y: 17.07))
        text3Path.addCurveToPoint(CGPoint(x: 82.75, y: 20.8), controlPoint1: CGPoint(x: 83.01, y: 18.8), controlPoint2: CGPoint(x: 82.92, y: 20.04))
        text3Path.addCurveToPoint(CGPoint(x: 81.73, y: 22.75), controlPoint1: CGPoint(x: 82.57, y: 21.57), controlPoint2: CGPoint(x: 82.24, y: 22.22))
        text3Path.addCurveToPoint(CGPoint(x: 78.16, y: 24.07), controlPoint1: CGPoint(x: 80.89, y: 23.63), controlPoint2: CGPoint(x: 79.7, y: 24.07))
        text3Path.addCurveToPoint(CGPoint(x: 74.62, y: 23.27), controlPoint1: CGPoint(x: 77.07, y: 24.07), controlPoint2: CGPoint(x: 75.89, y: 23.8))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 80.47, y: 15.54))
        text3Path.addLineToPoint(CGPoint(x: 80.47, y: 11.37))
        text3Path.addCurveToPoint(CGPoint(x: 78.55, y: 10.12), controlPoint1: CGPoint(x: 79.86, y: 10.54), controlPoint2: CGPoint(x: 79.22, y: 10.12))
        text3Path.addCurveToPoint(CGPoint(x: 77.02, y: 11.17), controlPoint1: CGPoint(x: 77.91, y: 10.12), controlPoint2: CGPoint(x: 77.4, y: 10.47))
        text3Path.addCurveToPoint(CGPoint(x: 76.46, y: 13.99), controlPoint1: CGPoint(x: 76.65, y: 11.87), controlPoint2: CGPoint(x: 76.46, y: 12.81))
        text3Path.addCurveToPoint(CGPoint(x: 78.23, y: 17.31), controlPoint1: CGPoint(x: 76.46, y: 16.21), controlPoint2: CGPoint(x: 77.05, y: 17.31))
        text3Path.addCurveToPoint(CGPoint(x: 80.47, y: 15.54), controlPoint1: CGPoint(x: 79.05, y: 17.31), controlPoint2: CGPoint(x: 79.79, y: 16.72))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 93.77, y: 19.37))
        text3Path.addCurveToPoint(CGPoint(x: 90.35, y: 20.01), controlPoint1: CGPoint(x: 92.57, y: 19.8), controlPoint2: CGPoint(x: 91.43, y: 20.01))
        text3Path.addCurveToPoint(CGPoint(x: 86.63, y: 18.4), controlPoint1: CGPoint(x: 88.78, y: 20.01), controlPoint2: CGPoint(x: 87.54, y: 19.48))
        text3Path.addCurveToPoint(CGPoint(x: 85.27, y: 14.01), controlPoint1: CGPoint(x: 85.72, y: 17.33), controlPoint2: CGPoint(x: 85.27, y: 15.87))
        text3Path.addCurveToPoint(CGPoint(x: 86.52, y: 9.79), controlPoint1: CGPoint(x: 85.27, y: 12.26), controlPoint2: CGPoint(x: 85.69, y: 10.85))
        text3Path.addCurveToPoint(CGPoint(x: 89.81, y: 8.18), controlPoint1: CGPoint(x: 87.35, y: 8.72), controlPoint2: CGPoint(x: 88.45, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 92.82, y: 9.75), controlPoint1: CGPoint(x: 91.19, y: 8.18), controlPoint2: CGPoint(x: 92.19, y: 8.71))
        text3Path.addCurveToPoint(CGPoint(x: 93.77, y: 14.71), controlPoint1: CGPoint(x: 93.46, y: 10.79), controlPoint2: CGPoint(x: 93.77, y: 12.45))
        text3Path.addLineToPoint(CGPoint(x: 87.94, y: 14.71))
        text3Path.addCurveToPoint(CGPoint(x: 90.9, y: 17.94), controlPoint1: CGPoint(x: 88.11, y: 16.86), controlPoint2: CGPoint(x: 89.1, y: 17.94))
        text3Path.addCurveToPoint(CGPoint(x: 93.77, y: 17.23), controlPoint1: CGPoint(x: 91.75, y: 17.94), controlPoint2: CGPoint(x: 92.71, y: 17.7))
        text3Path.addLineToPoint(CGPoint(x: 93.77, y: 19.37))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 87.91, y: 12.98))
        text3Path.addLineToPoint(CGPoint(x: 91.28, y: 12.98))
        text3Path.addCurveToPoint(CGPoint(x: 89.73, y: 10.09), controlPoint1: CGPoint(x: 91.28, y: 11.05), controlPoint2: CGPoint(x: 90.77, y: 10.09))
        text3Path.addCurveToPoint(CGPoint(x: 87.91, y: 12.98), controlPoint1: CGPoint(x: 88.68, y: 10.09), controlPoint2: CGPoint(x: 88.07, y: 11.05))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 98.99, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 98.99, y: 4.51))
        text3Path.addLineToPoint(CGPoint(x: 103.74, y: 4.51))
        text3Path.addCurveToPoint(CGPoint(x: 107.6, y: 8.29), controlPoint1: CGPoint(x: 106.31, y: 4.51), controlPoint2: CGPoint(x: 107.6, y: 5.77))
        text3Path.addCurveToPoint(CGPoint(x: 106.94, y: 10.86), controlPoint1: CGPoint(x: 107.6, y: 9.23), controlPoint2: CGPoint(x: 107.38, y: 10.08))
        text3Path.addCurveToPoint(CGPoint(x: 105.14, y: 12.63), controlPoint1: CGPoint(x: 106.51, y: 11.63), controlPoint2: CGPoint(x: 105.9, y: 12.22))
        text3Path.addLineToPoint(CGPoint(x: 109.28, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 106.07, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 102.93, y: 13.52))
        text3Path.addLineToPoint(CGPoint(x: 101.47, y: 13.52))
        text3Path.addLineToPoint(CGPoint(x: 101.47, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 98.99, y: 19.75))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 101.47, y: 11.43))
        text3Path.addLineToPoint(CGPoint(x: 102.08, y: 11.43))
        text3Path.addCurveToPoint(CGPoint(x: 104.95, y: 8.64), controlPoint1: CGPoint(x: 103.99, y: 11.43), controlPoint2: CGPoint(x: 104.95, y: 10.5))
        text3Path.addCurveToPoint(CGPoint(x: 102.39, y: 6.6), controlPoint1: CGPoint(x: 104.95, y: 7.28), controlPoint2: CGPoint(x: 104.1, y: 6.6))
        text3Path.addLineToPoint(CGPoint(x: 101.47, y: 6.6))
        text3Path.addLineToPoint(CGPoint(x: 101.47, y: 11.43))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 118.75, y: 19.37))
        text3Path.addCurveToPoint(CGPoint(x: 115.32, y: 20.01), controlPoint1: CGPoint(x: 117.54, y: 19.8), controlPoint2: CGPoint(x: 116.4, y: 20.01))
        text3Path.addCurveToPoint(CGPoint(x: 111.61, y: 18.4), controlPoint1: CGPoint(x: 113.75, y: 20.01), controlPoint2: CGPoint(x: 112.51, y: 19.48))
        text3Path.addCurveToPoint(CGPoint(x: 110.24, y: 14.01), controlPoint1: CGPoint(x: 110.7, y: 17.33), controlPoint2: CGPoint(x: 110.24, y: 15.87))
        text3Path.addCurveToPoint(CGPoint(x: 111.49, y: 9.79), controlPoint1: CGPoint(x: 110.24, y: 12.26), controlPoint2: CGPoint(x: 110.66, y: 10.85))
        text3Path.addCurveToPoint(CGPoint(x: 114.78, y: 8.18), controlPoint1: CGPoint(x: 112.32, y: 8.72), controlPoint2: CGPoint(x: 113.42, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 117.8, y: 9.75), controlPoint1: CGPoint(x: 116.16, y: 8.18), controlPoint2: CGPoint(x: 117.16, y: 8.71))
        text3Path.addCurveToPoint(CGPoint(x: 118.75, y: 14.71), controlPoint1: CGPoint(x: 118.43, y: 10.79), controlPoint2: CGPoint(x: 118.75, y: 12.45))
        text3Path.addLineToPoint(CGPoint(x: 112.92, y: 14.71))
        text3Path.addCurveToPoint(CGPoint(x: 115.87, y: 17.94), controlPoint1: CGPoint(x: 113.09, y: 16.86), controlPoint2: CGPoint(x: 114.07, y: 17.94))
        text3Path.addCurveToPoint(CGPoint(x: 118.75, y: 17.23), controlPoint1: CGPoint(x: 116.72, y: 17.94), controlPoint2: CGPoint(x: 117.68, y: 17.7))
        text3Path.addLineToPoint(CGPoint(x: 118.75, y: 19.37))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 112.88, y: 12.98))
        text3Path.addLineToPoint(CGPoint(x: 116.26, y: 12.98))
        text3Path.addCurveToPoint(CGPoint(x: 114.71, y: 10.09), controlPoint1: CGPoint(x: 116.26, y: 11.05), controlPoint2: CGPoint(x: 115.74, y: 10.09))
        text3Path.addCurveToPoint(CGPoint(x: 112.88, y: 12.98), controlPoint1: CGPoint(x: 113.66, y: 10.09), controlPoint2: CGPoint(x: 113.05, y: 11.05))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 125.98, y: 18.54))
        text3Path.addCurveToPoint(CGPoint(x: 123.26, y: 20.01), controlPoint1: CGPoint(x: 125.13, y: 19.52), controlPoint2: CGPoint(x: 124.23, y: 20.01))
        text3Path.addCurveToPoint(CGPoint(x: 121.26, y: 19.1), controlPoint1: CGPoint(x: 122.44, y: 20.01), controlPoint2: CGPoint(x: 121.77, y: 19.71))
        text3Path.addCurveToPoint(CGPoint(x: 120.49, y: 16.76), controlPoint1: CGPoint(x: 120.74, y: 18.5), controlPoint2: CGPoint(x: 120.49, y: 17.72))
        text3Path.addCurveToPoint(CGPoint(x: 121.73, y: 13.87), controlPoint1: CGPoint(x: 120.49, y: 15.51), controlPoint2: CGPoint(x: 120.9, y: 14.54))
        text3Path.addCurveToPoint(CGPoint(x: 125.3, y: 12.85), controlPoint1: CGPoint(x: 122.56, y: 13.19), controlPoint2: CGPoint(x: 123.75, y: 12.85))
        text3Path.addLineToPoint(CGPoint(x: 125.98, y: 12.85))
        text3Path.addLineToPoint(CGPoint(x: 125.98, y: 11.82))
        text3Path.addCurveToPoint(CGPoint(x: 124.31, y: 10.06), controlPoint1: CGPoint(x: 125.98, y: 10.65), controlPoint2: CGPoint(x: 125.42, y: 10.06))
        text3Path.addCurveToPoint(CGPoint(x: 121.31, y: 11.07), controlPoint1: CGPoint(x: 123.32, y: 10.06), controlPoint2: CGPoint(x: 122.32, y: 10.4))
        text3Path.addLineToPoint(CGPoint(x: 121.31, y: 8.97))
        text3Path.addCurveToPoint(CGPoint(x: 124.72, y: 8.18), controlPoint1: CGPoint(x: 122.46, y: 8.44), controlPoint2: CGPoint(x: 123.59, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 128.41, y: 11.72), controlPoint1: CGPoint(x: 127.18, y: 8.18), controlPoint2: CGPoint(x: 128.41, y: 9.36))
        text3Path.addLineToPoint(CGPoint(x: 128.41, y: 16.72))
        text3Path.addCurveToPoint(CGPoint(x: 129.12, y: 18.05), controlPoint1: CGPoint(x: 128.41, y: 17.61), controlPoint2: CGPoint(x: 128.65, y: 18.05))
        text3Path.addCurveToPoint(CGPoint(x: 129.45, y: 18.01), controlPoint1: CGPoint(x: 129.2, y: 18.05), controlPoint2: CGPoint(x: 129.32, y: 18.04))
        text3Path.addLineToPoint(CGPoint(x: 129.51, y: 19.72))
        text3Path.addCurveToPoint(CGPoint(x: 128.09, y: 20.01), controlPoint1: CGPoint(x: 128.98, y: 19.91), controlPoint2: CGPoint(x: 128.5, y: 20.01))
        text3Path.addCurveToPoint(CGPoint(x: 126.09, y: 18.54), controlPoint1: CGPoint(x: 127.05, y: 20.01), controlPoint2: CGPoint(x: 126.38, y: 19.52))
        text3Path.addLineToPoint(CGPoint(x: 125.98, y: 18.54))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 125.98, y: 16.9))
        text3Path.addLineToPoint(CGPoint(x: 125.98, y: 14.6))
        text3Path.addLineToPoint(CGPoint(x: 125.38, y: 14.6))
        text3Path.addCurveToPoint(CGPoint(x: 122.92, y: 16.46), controlPoint1: CGPoint(x: 123.74, y: 14.6), controlPoint2: CGPoint(x: 122.92, y: 15.22))
        text3Path.addCurveToPoint(CGPoint(x: 123.27, y: 17.51), controlPoint1: CGPoint(x: 122.92, y: 16.88), controlPoint2: CGPoint(x: 123.04, y: 17.23))
        text3Path.addCurveToPoint(CGPoint(x: 124.15, y: 17.94), controlPoint1: CGPoint(x: 123.51, y: 17.8), controlPoint2: CGPoint(x: 123.8, y: 17.94))
        text3Path.addCurveToPoint(CGPoint(x: 125.98, y: 16.9), controlPoint1: CGPoint(x: 124.75, y: 17.94), controlPoint2: CGPoint(x: 125.35, y: 17.59))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 137.6, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 137.6, y: 17.62))
        text3Path.addCurveToPoint(CGPoint(x: 134.52, y: 20.01), controlPoint1: CGPoint(x: 136.95, y: 19.21), controlPoint2: CGPoint(x: 135.92, y: 20.01))
        text3Path.addCurveToPoint(CGPoint(x: 131.86, y: 18.52), controlPoint1: CGPoint(x: 133.39, y: 20.01), controlPoint2: CGPoint(x: 132.5, y: 19.51))
        text3Path.addCurveToPoint(CGPoint(x: 130.89, y: 14.41), controlPoint1: CGPoint(x: 131.21, y: 17.52), controlPoint2: CGPoint(x: 130.89, y: 16.15))
        text3Path.addCurveToPoint(CGPoint(x: 131.98, y: 9.87), controlPoint1: CGPoint(x: 130.89, y: 12.51), controlPoint2: CGPoint(x: 131.26, y: 11))
        text3Path.addCurveToPoint(CGPoint(x: 134.92, y: 8.18), controlPoint1: CGPoint(x: 132.71, y: 8.75), controlPoint2: CGPoint(x: 133.69, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 137.6, y: 9.58), controlPoint1: CGPoint(x: 135.9, y: 8.18), controlPoint2: CGPoint(x: 136.79, y: 8.65))
        text3Path.addLineToPoint(CGPoint(x: 137.6, y: 3.49))
        text3Path.addLineToPoint(CGPoint(x: 140.14, y: 3.49))
        text3Path.addLineToPoint(CGPoint(x: 140.14, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 137.6, y: 19.75))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 137.6, y: 11.4))
        text3Path.addCurveToPoint(CGPoint(x: 135.64, y: 10.16), controlPoint1: CGPoint(x: 136.99, y: 10.57), controlPoint2: CGPoint(x: 136.33, y: 10.16))
        text3Path.addCurveToPoint(CGPoint(x: 134.15, y: 11.24), controlPoint1: CGPoint(x: 135.01, y: 10.16), controlPoint2: CGPoint(x: 134.52, y: 10.52))
        text3Path.addCurveToPoint(CGPoint(x: 133.59, y: 14.15), controlPoint1: CGPoint(x: 133.78, y: 11.96), controlPoint2: CGPoint(x: 133.59, y: 12.93))
        text3Path.addCurveToPoint(CGPoint(x: 135.44, y: 17.62), controlPoint1: CGPoint(x: 133.59, y: 16.46), controlPoint2: CGPoint(x: 134.21, y: 17.62))
        text3Path.addCurveToPoint(CGPoint(x: 137.6, y: 15.88), controlPoint1: CGPoint(x: 136.19, y: 17.62), controlPoint2: CGPoint(x: 136.91, y: 17.04))
        text3Path.addLineToPoint(CGPoint(x: 137.6, y: 11.4))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 150.96, y: 19.37))
        text3Path.addCurveToPoint(CGPoint(x: 147.53, y: 20.01), controlPoint1: CGPoint(x: 149.75, y: 19.8), controlPoint2: CGPoint(x: 148.61, y: 20.01))
        text3Path.addCurveToPoint(CGPoint(x: 143.82, y: 18.4), controlPoint1: CGPoint(x: 145.96, y: 20.01), controlPoint2: CGPoint(x: 144.72, y: 19.48))
        text3Path.addCurveToPoint(CGPoint(x: 142.45, y: 14.01), controlPoint1: CGPoint(x: 142.91, y: 17.33), controlPoint2: CGPoint(x: 142.45, y: 15.87))
        text3Path.addCurveToPoint(CGPoint(x: 143.7, y: 9.79), controlPoint1: CGPoint(x: 142.45, y: 12.26), controlPoint2: CGPoint(x: 142.87, y: 10.85))
        text3Path.addCurveToPoint(CGPoint(x: 146.99, y: 8.18), controlPoint1: CGPoint(x: 144.53, y: 8.72), controlPoint2: CGPoint(x: 145.63, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 150.01, y: 9.75), controlPoint1: CGPoint(x: 148.37, y: 8.18), controlPoint2: CGPoint(x: 149.37, y: 8.71))
        text3Path.addCurveToPoint(CGPoint(x: 150.96, y: 14.71), controlPoint1: CGPoint(x: 150.64, y: 10.79), controlPoint2: CGPoint(x: 150.96, y: 12.45))
        text3Path.addLineToPoint(CGPoint(x: 145.13, y: 14.71))
        text3Path.addCurveToPoint(CGPoint(x: 148.08, y: 17.94), controlPoint1: CGPoint(x: 145.3, y: 16.86), controlPoint2: CGPoint(x: 146.28, y: 17.94))
        text3Path.addCurveToPoint(CGPoint(x: 150.96, y: 17.23), controlPoint1: CGPoint(x: 148.93, y: 17.94), controlPoint2: CGPoint(x: 149.89, y: 17.7))
        text3Path.addLineToPoint(CGPoint(x: 150.96, y: 19.37))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 145.09, y: 12.98))
        text3Path.addLineToPoint(CGPoint(x: 148.47, y: 12.98))
        text3Path.addCurveToPoint(CGPoint(x: 146.92, y: 10.09), controlPoint1: CGPoint(x: 148.47, y: 11.05), controlPoint2: CGPoint(x: 147.95, y: 10.09))
        text3Path.addCurveToPoint(CGPoint(x: 145.09, y: 12.98), controlPoint1: CGPoint(x: 145.87, y: 10.09), controlPoint2: CGPoint(x: 145.26, y: 11.05))
        text3Path.closePath()
        text3Path.moveToPoint(CGPoint(x: 153.58, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 153.58, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 156.11, y: 8.44))
        text3Path.addLineToPoint(CGPoint(x: 156.11, y: 10.57))
        text3Path.addCurveToPoint(CGPoint(x: 159.11, y: 8.18), controlPoint1: CGPoint(x: 156.77, y: 8.98), controlPoint2: CGPoint(x: 157.77, y: 8.18))
        text3Path.addCurveToPoint(CGPoint(x: 159.58, y: 8.25), controlPoint1: CGPoint(x: 159.27, y: 8.18), controlPoint2: CGPoint(x: 159.43, y: 8.2))
        text3Path.addLineToPoint(CGPoint(x: 159.58, y: 10.97))
        text3Path.addCurveToPoint(CGPoint(x: 158.58, y: 10.73), controlPoint1: CGPoint(x: 159.22, y: 10.81), controlPoint2: CGPoint(x: 158.89, y: 10.73))
        text3Path.addCurveToPoint(CGPoint(x: 156.11, y: 12.57), controlPoint1: CGPoint(x: 157.57, y: 10.73), controlPoint2: CGPoint(x: 156.75, y: 11.34))
        text3Path.addLineToPoint(CGPoint(x: 156.11, y: 19.75))
        text3Path.addLineToPoint(CGPoint(x: 153.58, y: 19.75))
        text3Path.closePath()
        fUIBBlue.setFill()
        text3Path.fill()
    }

    //// Generated Images

    public class var imageOfRefresh: UIImage {
        if Cache.imageOfRefresh != nil {
            return Cache.imageOfRefresh!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 60, height: 60), false, 0)
            DrudgeStyleKit.drawRefresh()

        Cache.imageOfRefresh = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfRefresh!
    }

    public class var imageOfPicture: UIImage {
        if Cache.imageOfPicture != nil {
            return Cache.imageOfPicture!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 60, height: 60), false, 0)
            DrudgeStyleKit.drawPicture()

        Cache.imageOfPicture = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfPicture!
    }

    public class var imageOfFilter: UIImage {
        if Cache.imageOfFilter != nil {
            return Cache.imageOfFilter!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 25, height: 25), false, 0)
            DrudgeStyleKit.drawFilter()

        Cache.imageOfFilter = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfFilter!
    }

    public class var imageOfNoFilter: UIImage {
        if Cache.imageOfNoFilter != nil {
            return Cache.imageOfNoFilter!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 25, height: 25), false, 0)
            DrudgeStyleKit.drawNoFilter()

        Cache.imageOfNoFilter = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfNoFilter!
    }

    public class var imageOfHeadline_icon: UIImage {
        if Cache.imageOfHeadline_icon != nil {
            return Cache.imageOfHeadline_icon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 20, height: 20), false, 0)
            DrudgeStyleKit.drawHeadline_icon()

        Cache.imageOfHeadline_icon = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfHeadline_icon!
    }

    public class var imageOfTop_story: UIImage {
        if Cache.imageOfTop_story != nil {
            return Cache.imageOfTop_story!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 20, height: 20), false, 0)
            DrudgeStyleKit.drawTop_story()

        Cache.imageOfTop_story = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfTop_story!
    }

    public class var imageOfColumn: UIImage {
        if Cache.imageOfColumn != nil {
            return Cache.imageOfColumn!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 20, height: 20), false, 0)
            DrudgeStyleKit.drawColumn()

        Cache.imageOfColumn = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfColumn!
    }

    public class var imageOfDLogo: UIImage {
        if Cache.imageOfDLogo != nil {
            return Cache.imageOfDLogo!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 512, height: 512), false, 0)
            DrudgeStyleKit.drawDLogo()

        Cache.imageOfDLogo = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfDLogo!
    }

    public class var imageOfDNavLogo: UIImage {
        if Cache.imageOfDNavLogo != nil {
            return Cache.imageOfDNavLogo!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 161, height: 25), false, 0)
            DrudgeStyleKit.drawDNavLogo()

        Cache.imageOfDNavLogo = UIGraphicsGetImageFromCurrentImageContext().imageWithRenderingMode(.AlwaysOriginal)
        UIGraphicsEndImageContext()

        return Cache.imageOfDNavLogo!
    }

    //// Customization Infrastructure

    @IBOutlet var refreshTargets: [AnyObject]! {
        get { return Cache.refreshTargets }
        set {
            Cache.refreshTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfRefresh)
            }
        }
    }

    @IBOutlet var pictureTargets: [AnyObject]! {
        get { return Cache.pictureTargets }
        set {
            Cache.pictureTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfPicture)
            }
        }
    }

    @IBOutlet var filterTargets: [AnyObject]! {
        get { return Cache.filterTargets }
        set {
            Cache.filterTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfFilter)
            }
        }
    }

    @IBOutlet var noFilterTargets: [AnyObject]! {
        get { return Cache.noFilterTargets }
        set {
            Cache.noFilterTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfNoFilter)
            }
        }
    }

    @IBOutlet var headline_iconTargets: [AnyObject]! {
        get { return Cache.headline_iconTargets }
        set {
            Cache.headline_iconTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfHeadline_icon)
            }
        }
    }

    @IBOutlet var top_storyTargets: [AnyObject]! {
        get { return Cache.top_storyTargets }
        set {
            Cache.top_storyTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfTop_story)
            }
        }
    }

    @IBOutlet var columnTargets: [AnyObject]! {
        get { return Cache.columnTargets }
        set {
            Cache.columnTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfColumn)
            }
        }
    }

    @IBOutlet var dLogoTargets: [AnyObject]! {
        get { return Cache.dLogoTargets }
        set {
            Cache.dLogoTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfDLogo)
            }
        }
    }

    @IBOutlet var dNavLogoTargets: [AnyObject]! {
        get { return Cache.dNavLogoTargets }
        set {
            Cache.dNavLogoTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: DrudgeStyleKit.imageOfDNavLogo)
            }
        }
    }

}



extension UIColor {
    func colorWithHue(newHue: CGFloat) -> UIColor {
        var saturation: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(nil, saturation: &saturation, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: newHue, saturation: saturation, brightness: brightness, alpha: alpha)
    }
    func colorWithSaturation(newSaturation: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: nil, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: hue, saturation: newSaturation, brightness: brightness, alpha: alpha)
    }
    func colorWithBrightness(newBrightness: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: nil, alpha: &alpha)
        return UIColor(hue: hue, saturation: saturation, brightness: newBrightness, alpha: alpha)
    }
    func colorWithAlpha(newAlpha: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, brightness: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: nil)
        return UIColor(hue: hue, saturation: saturation, brightness: brightness, alpha: newAlpha)
    }
    func colorWithHighlight(highlight: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-highlight) + highlight, green: green * (1-highlight) + highlight, blue: blue * (1-highlight) + highlight, alpha: alpha * (1-highlight) + highlight)
    }
    func colorWithShadow(shadow: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-shadow), green: green * (1-shadow), blue: blue * (1-shadow), alpha: alpha * (1-shadow) + shadow)
    }
}
